COL JOB        FORMAT A8    HEADING "JOB"
COL LOG_USER   FORMAT A22   HEADING "LOG_USER"
COL PRIV_USER  FORMAT A22   HEADING "PRIV_USER"
COL BRK        FORMAT A3    HEADING "BRK"
COL RUNN       FORMAT A4    HEADING "RUNN"
COL FAILURES   FORMAT 99999 HEADING "FALHAS"
COL WHAT       FORMAT A123  HEADING "WHAT" PRINT
rem COL WHAT       FORMAT A123  HEADING "WHAT" PRINT NEWLINE

COL INTERVAL FORMAT A32 PRINT

SET PAGES 400 LINES 300 LONG 300 TERMOUT OFF FEED OFF VERIFY OFF UNDERLINE ON

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYyy-HH24:MI';

SET TERMOUT ON

PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SELECT SYSDATE "HORA ATUAL" FROM DUAL
/

PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WITH V AS
(
  SELECT /*+ RULE */
    LPAD(J.JOB,8,'0') JOB, J.LOG_USER, J.PRIV_USER, J.LAST_DATE,
    J.NEXT_DATE, J.INTERVAL, DECODE(J.BROKEN, 'Y', 'YES', ' NO') BRK,
    DECODE(R.JOB, NULL, '  NO', LPAD(R.SID, 4, ' ') ) RUNN, J.FAILURES,
    J.WHAT
  FROM DBA_JOBS J, DBA_JOBS_RUNNING R
  WHERE J.JOB = R.JOB(+)
)
SELECT V.*
FROM V
WHERE V.LOG_USER LIKE UPPER( '&jowner.' )
AND TRIM(V.RUNN) <> DECODE( '&ativos', '1', 'NO', 'TODOS' )
ORDER BY 1
/

SET FEED 6 PAGES 66 UNDERLINE ON VERIFY ON

COL JOB        CLEAR
COL INTERVAL   CLEAR
COL WHAT       CLEAR
COL FAILURES   CLEAR
COL RUNN       CLEAR

PROMPT
