SET DEFINE ON

DEFINE P_TBS=&1.
DEFINE P_OWNER=&2.
DEFINE P_SEG=&3.
DEFINE P_PCTOCUP=0
DEFINE P_MEGAS=1024
DEFINE P_RESUMO=Sim

@@do.monitsegs.sql

PROMPT Para obter o detalhamento de partições use @monitsegsd &p_tbs. &p_owner. &p_seg.
PROMPT

UNDEFINE P_TBS
UNDEFINE P_OWNER
UNDEFINE P_SEG
UNDEFINE P_PCTOCUP
UNDEFINE P_MEGAS
UNDEFINE P_RESUMO
UNDEFINE 1
UNDEFINE 2
UNDEFINE 3


