SET TERMOUT OFF FEEDBACK OFF VERIFY OFF PAGES 500 LINES 200

COL STMT_ID NEW_VALUE STMT_ID NOPRINT
DEFINE P1=&1.
DEFINE P_HASH='0'
DEFINE P_ADDR='0'
DEFINE P_CHILD_ADDR='0'
DEFINE P_QTCOPIAS='-1'
DEFINE P_VERSAO=''
DEFINE P_WHERE_CURSOR=''
DEFINE P_SQL_ID=''
DEFINE P_SQL_PATCH=''
DEFINE P_SQL_PROFILE=''
DEFINE P_SQL_PLAN_BASELINE=''
DEFINE P_OUTLINE_CATEGORY=''

SELECT LOWER(SYS_CONTEXT( 'USERENV', 'TERMINAL' )) STMT_ID
FROM DUAL
/

DELETE sys.PLAN_TABLE$ WHERE STATEMENT_ID = '&STMT_ID.'
/
COMMIT
/

SET TERMOUT ON

@explain.sql &STMT_ID.

@do.expplan.sql &STMT_ID.

ROLLBACK
/

PROMPT

COL STMT_ID CLEAR

SET FEEDBACK 6 VERIFY ON PAGES 100

