SET LINES 2200 VERIFY OFF

COL LAST_START_DATE FORMAT A20 TRUNC
COL NEXT_RUN_DATE FORMAT A20 TRUNC
COL LAST_RUN_DURATION FORMAT A20 TRUNC
COL JOB_ACTION FORMAT A60 TRUNC
COL REPEAT_INTERVAL FORMAT A40 TRUNC
SELECT 
   OWNER, JOB_NAME, STATE
  ,TO_CHAR(NEXT_RUN_DATE, 'DD/MM/YYYY HH24:MI TZH:TZM') NEXT_RUN_DATE
  ,REPEAT_INTERVAL      
  ,END_DATE
  ,FAILURE_COUNT
  ,TO_CHAR(LAST_START_DATE, 'DD/MM HH24:MI TZH:TZM') LAST_START_DATE
  --,TO_CHAR(LAST_START_DATE, 'DD/MM HH24:MI TZH:TZM') LAST_START_DATE
  --,TO_CHAR(LAST_RUN_DURATION, 'HH24:MI:SS' ) LAST_RUN_DURATION
  ,CAST( LAST_RUN_DURATION AS INTERVAL DAY(2) TO SECOND(0) ) LAST_RUN_DURATION
  ,JOB_ACTION
  --, COMMENTS 
  , JOB_CREATOR
FROM DBA_SCHEDULER_JOBS
WHERE OWNER LIKE upper('&1')
/
SET LINES 220 VERIFY OFF
