SET DEFINE ON

DEFINE DONO='&1.'
DEFINE NOME='&2.'
DEFINE TIPO='%'

SET VERIFY OFF TRIMSPOOL ON PAGES 0 FEEDBACK OFF TERMOUT OFF LINES 500

SPOOL xGerarFontes.Sql

SELECT DISTINCT
 'PROMPT Gerando ' || TYPE || ' ' || OWNER || ' ' || NAME || CHR(10) ||
 '@@Do.GetFontesDBA.Sql "' || TYPE || '" ' || OWNER || ' ' || NAME
FROM DBA_SOURCE
WHERE UPPER ( NAME ) LIKE UPPER( '&NOME' )
AND OWNER LIKE UPPER( '&DONO' )
AND TYPE LIKE UPPER( '&TIPO' )
/

SPOOL OFF
SET PAGES 100 FEEDBACK 6 TERMOUT ON

@xGerarFontes.Sql

HOST DEL xGerarFontes.Sql
