col name for a20
 SELECT LOCAL.THREAD#, LOCAL.SEQUENCE# 
 FROM
 (SELECT THREAD#, SEQUENCE# FROM V$ARCHIVED_LOG WHERE DEST_ID=1) LOCAL 
 WHERE
 LOCAL.SEQUENCE# NOT IN
 (SELECT SEQUENCE# FROM V$ARCHIVED_LOG 
  WHERE DEST_ID<>1 AND THREAD# = LOCAL.THREAD#);

