col status for 99999
select begin_time
--,snap_id
--,UNDOTSN   ,UNDOBLKS   ,TXNCOUNT 
,MAXQUERYLEN ,MAXQUERYID ,MAXCONCURRENCY 
--,UNXPSTEALCNT ,UNXPBLKRELCNT ,UNXPBLKREUCNT
,EXPSTEALCNT ,EXPBLKRELCNT
--, EXPBLKREUCNT, SSOLDERRCNT
, NOSPACEERRCNT, ACTIVEBLKS, UNEXPIREDBLKS, EXPIREDBLKS, TUNED_UNDORETENTION
--,STATUS
--, SPCPRS_RETENTION
from v$undostat
where begin_time > trunc(sysdate)
order by begin_time
/
