COL OWNER     FORMAT A15     HEAD DONO
COL DIRETORIO FORMAT A30     HEAD DIRETORIO
COL PATH      FORMAT A70     HEAD CAMINHO
SELECT
  OWNER, DIRECTORY_NAME DIRETORIO, DIRECTORY_PATH PATH/* ,
  CURSOR (SELECT GRANTEE, PRIVILEGE FROM DBA_TAB_PRIVS WHERE TABLE_NAME = DIRECTORY_NAME) */
FROM DBA_DIRECTORIES
ORDER BY PATH
/
COL OWNER     CLEAR
COL DIRETORIO CLEAR
COL PATH      CLEAR


