-- Bug que gera desconexão quando consulta é realizada contra V$SQL_PLAN. Workaround abaixo:
--alter session set "_cursor_plan_unparse_enabled"=false;

DELETE sys.PLAN_TABLE$
WHERE STATEMENT_ID = '&1.'
/

INSERT INTO sys.PLAN_TABLE$
(
  BYTES
 ,ACCESS_PREDICATES
 ,CARDINALITY
 ,COST
 ,CPU_COST
 ,DEPTH
 ,DISTRIBUTION
 ,FILTER_PREDICATES
 ,ID
 ,IO_COST
 ,OBJECT_ALIAS
 ,OBJECT_NAME
 ,OBJECT_NODE
 ,OBJECT_OWNER
 ,OBJECT_TYPE
 ,OPERATION
 ,OPTIMIZER
 ,OPTIONS
 ,OTHER
 ,OTHER_TAG
 --,OTHER_XML
 ,PARENT_ID
 ,PARTITION_ID
 ,PARTITION_START
 ,PARTITION_STOP
 ,POSITION
 ,PROJECTION
 ,QBLOCK_NAME
 ,REMARKS
 ,SEARCH_COLUMNS
 ,TEMP_SPACE
 ,TIME
 ,TIMESTAMP
 ,STATEMENT_ID
 ,PLAN_ID
)
SELECT
  BYTES
 ,ACCESS_PREDICATES
 ,CARDINALITY
 ,COST
 ,CPU_COST
 ,DEPTH
 ,DISTRIBUTION
 ,FILTER_PREDICATES
 ,ID
 ,IO_COST
 ,OBJECT_ALIAS
 ,OBJECT_NAME
 ,OBJECT_NODE
 ,OBJECT_OWNER
 ,OBJECT_TYPE
 ,OPERATION
 ,OPTIMIZER
 ,OPTIONS
 ,OTHER
 ,OTHER_TAG
 --,OTHER_XML
 ,PARENT_ID
 ,PARTITION_ID
 ,PARTITION_START
 ,PARTITION_STOP
 ,POSITION
 ,PROJECTION
 ,QBLOCK_NAME
 ,REMARKS
 ,SEARCH_COLUMNS
 ,TEMP_SPACE
 ,TIME
 ,SYSTIMESTAMP, '&1.' 
 , PLAN_HASH_VALUE
FROM GV$SQL_PLAN
WHERE HASH_VALUE = &1. AND ADDRESS = '&2.'
AND CHILD_NUMBER =
 ( SELECT MAX( CHILD_NUMBER ) FROM GV$SQL_PLAN WHERE HASH_VALUE = &1. AND ADDRESS = '&2.' )
/

SELECT DISTINCT PLAN_ID PLAN_HASH_VALUE
FROM sys.PLAN_TABLE$
WHERE STATEMENT_ID = '&1.'
/

@do.expplan.sql &1.

SELECT DISTINCT
  P.SQL_ID, P.CHILD_NUMBER VERSION#, P.HASH_VALUE, P.ADDRESS, P.PLAN_HASH_VALUE
FROM GV$SQL_PLAN P
--WHERE P.HASH_VALUE = '&1.' AND P.ADDRESS = '&2.'
WHERE P.SQL_ID = '&P_SQL_ID.'
ORDER BY 1, 2
/
/*

SELECT DISTINCT
  P.SQL_ID, P.HASH_VALUE, P.CHILD_NUMBER VERSION#, P.PLAN_HASH_VALUE,
  S.USERS_EXECUTING, S.LOADS, S.FIRST_LOAD_TIME
FROM V$SQL_PLAN P, V$SQL S
WHERE P.HASH_VALUE = '&1.' AND P.ADDRESS = '&2.'
AND P.CHILD_ADDRESS = S.CHILD_ADDRESS
ORDER BY 1, 2, 3


S.OPEN_VERSIONS
S.USERS_OPENING
S.FETCHES
S.EXECUTIONS
S.USERS_EXECUTING
S.LOADS
S.FIRST_LOAD_TIME
S.INVALIDATIONS
*/



