SET VERIFY OFF FEED OFF

COL TABLE_OWNER FORMAT A20
COL TABLE_NAME FORMAT A30
COL "TRIGGER" FORMAT A45
COL TRIGGER_TYPE FORMAT A16
COL TRIGGERING_EVENT FORMAT A35

SELECT OWNER || '.' || TRIGGER_NAME "TRIGGER", TRIGGERING_EVENT, TRIGGER_TYPE, STATUS, TABLE_OWNER, TABLE_NAME
FROM DBA_TRIGGERS
WHERE TABLE_OWNER LIKE UPPER('&1.') AND TABLE_NAME LIKE UPPER('&2.')
ORDER BY 1
/

PROMPT

COL "TRIGGER" CLEAR
COL TRIGGER_TYPE CLEAR
COL TRIGGERING_EVENT CLEAR

SET VERIFY ON FEED 6

