col task for a45 word_wrapped
col description for a25 word_wrapped
col EXECUTION_DESCRIPTION for a30 word_wrapped
col ERROR_MESSAGE for a30 word_wrapped
col status_MESSAGE for a30 word_wrapped

select 
OWNER||'.'||TASK_NAME task
--,DESCRIPTION
--,TASK_ID
,ADVISOR_NAME
--,CREATED
,LAST_MODIFIED
--,PARENT_TASK_ID,PARENT_RXEC_ID
--,LAST_EXECUTION
--,EXECUTION_TYPE
--,EXECUTION_TYPE#,EXECUTION_DESCRIPTION,EXECUTION_START,EXECUTION_END
,STATUS,STATUS_MESSAGE,PCT_COMPLETION_TIME,PROGRESS_METRIC,METRIC_UNITS
--,ACTIVITY_COUNTER,RECOMMENDATION_COUNT
,ERROR_MESSAGE
,SOURCE,HOW_CREATED,READ_ONLY,SYSTEM_TASK,ADVISOR_ID,STATUS#
from DBA_ADVISOR_TASKS
where CREATED > trunc(sysdate) -1
and HOW_CREATED !='AUTO'
/
