col status for 99999
select begin_time
--,snap_id
--,UNDOTSN   ,UNDOBLKS   ,TXNCOUNT 
,MAXQUERYLEN ,MAXQUERYSQLID ,MAXCONCURRENCY 
--,UNXPSTEALCNT ,UNXPBLKRELCNT ,UNXPBLKREUCNT
,EXPSTEALCNT ,EXPBLKRELCNT
--, EXPBLKREUCNT, SSOLDERRCNT
, NOSPACEERRCNT, ACTIVEBLKS, UNEXPIREDBLKS, EXPIREDBLKS, TUNED_UNDORETENTION,     STATUS
--, SPCPRS_RETENTION
, RUNAWAYQUERYSQLID
from WRH$_UNDOSTAT 
where begin_time > trunc(sysdate)
order by snap_id
/
