col name for a20
col seq for a10

  SELECT
--NAME
DEST_ID
,THREAD#||':'||SEQUENCE# seq
--,RESETLOGS_CHANGE#,RESETLOGS_TIME,RESETLOGS_ID
--,FIRST_CHANGE#,FIRST_TIME
--,NEXT_CHANGE#,NEXT_TIME
,STANDBY_DEST
,ARCHIVED
,APPLIED
,DELETED
,to_char(COMPLETION_TIME,'YYYY-MON-DD HH24:MI')
,BLOCKS
,BLOCK_SIZE
,CREATOR
,REGISTRAR
,STATUS
--,DICTIONARY_BEGIN,DICTIONARY_END
--,END_OF_REDO
,BACKUP_COUNT
,ARCHIVAL_THREAD#
--,ACTIVATION#
--,IS_RECOVERY_DEST_FILE
--,COMPRESSED
--,FAL
--,END_OF_REDO_TYPE
FROM V$ARCHIVED_LOG local 
WHERE 
COMPLETION_TIME > trunc(sysdate-1)
--and dest_id!=1
order by FIRST_CHANGE#,COMPLETION_TIME
/

