select REQUEST_FAILURES, round(LAST_FAILURE_SIZE/1024/1024,2) LAST_FAILURE_SIZE_MB
, ABORTED_REQUEST_THRESHOLD, ABORTED_REQUESTS, round(LAST_ABORTED_SIZE/1024/1024,2) LAST_ABORTED_SIZE_MB
, REQUESTS, REQUEST_MISSES, round(REQUEST_MISSES/REQUESTS*100,2) MISS_PCT
from V$SHARED_POOL_RESERVED;
